 const GET_MOVIES='GET_POPULAR_MOVIES';
 const SET_CURRENT_PAGE='SET_CURRENT_PAGE';
 const SET_TOTAL_COUNT='SET_TOTAL_COUNT';
 const GET_POSTERS='GET_POSTERS';
 const GET_DETAILS='GET_DETAILS';
 const GET_GENRES='GET_GENRES';
 const GET_GENRES_MOVIES='GET_GENRES_MOVIES';
 const SET_LIGHT='SET_LIGHT';
const  SET_DARK='SET_DARK';
const SET_VALUE='SET_VALUE';
const CLEAR_STATE='CLEAR_STATE';
 const SET_LOGIN = 'SET_LOGIN';

export {GET_MOVIES,SET_CURRENT_PAGE,SET_TOTAL_COUNT,GET_POSTERS,GET_DETAILS,GET_GENRES,GET_GENRES_MOVIES,SET_LIGHT,SET_DARK,
SET_VALUE,CLEAR_STATE,SET_LOGIN}